project:
  type: website
  output-dir: docs
  
website:
  title: "RfDS2solutions"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - solutions.qmd
      - about.qmd
  
format:
  html:
    theme: flatly
    css: styles.css
    toc: true

editor: visual

