---
title: "Chapter 7"
author: "Aditya Dahiya"
date: 2023-08-08
execute: 
  warning: false
  message: false
  error: false
  cache: true
filters:
  - social-share
share:
  permalink: "https://aditya-dahiya.github.io/RfDS2solutions/Chapter7.html"
  description: "Solutions: R for Data Science (2e)"
  twitter: true
  facebook: true
  linkedin: true
  email: true
---

# 7.3 Exercises

### Question 1

**Go to the RStudio Tips Twitter account, <https://twitter.com/rstudiotips> and find one tip that looks interesting. Practice using it!**

One tip that I found interesting is the use of `Ctrl + Shift + P` to open the R-Studio Command Palette. I have embedded the tweet here by inserting a simple HTML block, and pasting the HTML code from `public.twitter.com` [link](https://publish.twitter.com/?query=https%3A%2F%2Ftwitter.com%2Frstudiotips%2Fstatus%2F1585380805630914561&widget=Tweet).

```{=html}
<blockquote class="twitter-tweet"><p lang="en" dir="ltr">Access it with Ctrl + Shift + P (Windows / Linux) or Cmd + Shift + P (macOS)!<a href="https://twitter.com/hashtag/rstats?src=hash&amp;ref_src=twsrc%5Etfw">#rstats</a> <a href="https://t.co/pWAYHGCWRr">https://t.co/pWAYHGCWRr</a></p>&mdash; RStudio Tips (@rstudiotips) <a href="https://twitter.com/rstudiotips/status/1585380805630914561?ref_src=twsrc%5Etfw">October 26, 2022</a></blockquote> <script async src="https://platform.twitter.com/widgets.js" charset="utf-8"></script>
```
### Question 2

**What other common mistakes will RStudio diagnostics report? Read <https://support.posit.co/hc/en-us/articles/205753617-Code-Diagnostics> to find out.**

Some of the common mistakes that RStudio diagnostics will report are:\--

1.  It can detect if a variable named in a function has not yet been defined (i.e. the variable used has no definition in scope), or is misspelt.

2.  It can detect if a variable has been defined, but is not being used within a function.

3.  It can detect the missing punctuation, i.e. a missing comma or missing brackets.

4.  It can detect whether the call within a function can work or not, i.e., whether the arguments to a function are matched, partially matched or unmatched.

5.  It can detect if an essential argument to a function is missing.

6.  It can provide us `R` code style diagnostics, e.g. white-space etc.

7.  It can even detect mistakes in other languages such as `C` , `C++` , `JavaScript` and `Python` .
