---
title: "Chapter 30"
subtitle: "Quarto Formats"
author: "Aditya Dahiya"
date: 2023-07-25
execute: 
  warning: false
  message: false
  cache: true
---

# 30.5 Interactivity

```{r}
#| label: setup
library(DT)
library(tidyverse)
library(knitr)
```

## 30.5.1. htmlwidgets

Let us try to create an interactive map in HTML below @fig-leaflet:---̥

```{r}
#| label: fig-leaflet
#| fig-cap: "A map of Chandigarh, India using Leaflet"
#| fig-cap-location: top


library(leaflet)
leaflet() |>
  setView(76.801175, 30.761403, zoom = 14) |> 
  addTiles() |>
  addMarkers(76.801175, 30.761403, 
             popup = "Haryana Civil Secretariat")  |>
  addMarkers(76.803773534,
             30.752910586,
             popup = "Rock Garden")
```

#### Using `DT` for interactive tables:\-\--

An example of using `DT` for an interactive table is at @fig-DTtable :\-\--

```{r}
#| label: fig-DTtable
#| fig-cap: "A visually pleasing table produced using DT package"
#| fig-cap-location: top
diamonds |>
  filter(carat > 3) |>
  datatable(colnames = c("Carat", "Cut", "Color",
                         "Clarity", "Depth", "Table",
                         "Price", "X", "Y", "Z"),
            rownames = FALSE)
```
